-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bom
(
    bom_id serial NOT NULL,
    carport_id integer NOT NULL,
    variant_id integer NOT NULL,
    amount integer NOT NULL,
    CONSTRAINT bom_pkey PRIMARY KEY (bom_id)
);

CREATE TABLE IF NOT EXISTS public.carport
(
    carport_id serial NOT NULL,
    order_id integer NOT NULL,
    height_in_mm integer NOT NULL,
    length_in_mm integer NOT NULL,
    width_in_mm integer NOT NULL,
    CONSTRAINT carport_pkey PRIMARY KEY (carport_id)
);

CREATE TABLE IF NOT EXISTS public.carport_roof
(
    roof_id serial NOT NULL,
    carport_id integer NOT NULL,
    material character varying(100) COLLATE pg_catalog."default",
    tilt_in_degrees integer,
    CONSTRAINT carport_roof_pkey PRIMARY KEY (roof_id)
);

CREATE TABLE IF NOT EXISTS public.carport_shed
(
    shed_id serial NOT NULL,
    carport_id integer NOT NULL,
    length_in_mm integer NOT NULL,
    width_in_mm integer NOT NULL,
    floor character varying(100) COLLATE pg_catalog."default",
    wall_cladding character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT shed_pkey PRIMARY KEY (shed_id)
);

CREATE TABLE IF NOT EXISTS public.contact_info
(
    contact_info_id serial NOT NULL,
    full_name character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    address character varying(500) COLLATE pg_catalog."default" NOT NULL,
    zip_code integer NOT NULL,
    city character varying(500) COLLATE pg_catalog."default" NOT NULL,
    phone_number integer NOT NULL,
    email character varying(998) COLLATE pg_catalog."default" NOT NULL,
    user_id integer,
    send_ads_to_email boolean NOT NULL DEFAULT false,
    CONSTRAINT contact_info_pkey PRIMARY KEY (contact_info_id)
);

CREATE TABLE IF NOT EXISTS public.material
(
    material_id serial NOT NULL,
    category character varying(50) COLLATE pg_catalog."default" NOT NULL,
    material character varying(50) COLLATE pg_catalog."default" NOT NULL,
    treatment character varying(50) COLLATE pg_catalog."default",
    unit character varying(20) COLLATE pg_catalog."default" NOT NULL,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT material_pkey PRIMARY KEY (material_id)
);

CREATE TABLE IF NOT EXISTS public."order"
(
    order_id serial NOT NULL,
    price_suggested_in_oere integer NOT NULL,
    price_actual_in_oere integer,
    date_requested timestamp without time zone NOT NULL,
    date_approved timestamp without time zone,
    date_finished timestamp without time zone,
    status character varying(100) COLLATE pg_catalog."default" NOT NULL,
    contact_info_id integer,
    user_comment character varying(2000) COLLATE pg_catalog."default",
    CONSTRAINT order_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.specific
(
    specific_id serial NOT NULL,
    material_id integer NOT NULL,
    width_in_mm integer,
    height_in_mm integer,
    direction character varying(20) COLLATE pg_catalog."default",
    angle_in_degrees integer,
    CONSTRAINT specific_pkey PRIMARY KEY (specific_id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    user_id serial NOT NULL,
    email character varying(998) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    role character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT USER,
    CONSTRAINT user_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.variant
(
    variant_id serial NOT NULL,
    specific_id integer NOT NULL,
    length_in_mm integer,
    amount_pr_unit integer,
    price_in_oere integer NOT NULL,
    is_obsolete boolean NOT NULL,
    CONSTRAINT variant_pkey PRIMARY KEY (variant_id)
);

ALTER TABLE IF EXISTS public.bom
    ADD CONSTRAINT bom_carport_id_fkey FOREIGN KEY (carport_id)
        REFERENCES public.carport (carport_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.bom
    ADD CONSTRAINT bom_carport_id_fkey1 FOREIGN KEY (carport_id)
        REFERENCES public.carport (carport_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.bom
    ADD CONSTRAINT bom_carport_id_fkey2 FOREIGN KEY (carport_id)
        REFERENCES public.carport (carport_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.bom
    ADD CONSTRAINT bom_carport_id_fkey3 FOREIGN KEY (carport_id)
        REFERENCES public.carport (carport_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.bom
    ADD CONSTRAINT bom_variant_id_fkey FOREIGN KEY (variant_id)
        REFERENCES public.variant (variant_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.bom
    ADD CONSTRAINT bom_variant_id_fkey1 FOREIGN KEY (variant_id)
        REFERENCES public.variant (variant_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.bom
    ADD CONSTRAINT bom_variant_id_fkey2 FOREIGN KEY (variant_id)
        REFERENCES public.variant (variant_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.bom
    ADD CONSTRAINT bom_variant_id_fkey3 FOREIGN KEY (variant_id)
        REFERENCES public.variant (variant_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.carport
    ADD CONSTRAINT carport_order_id_fkey FOREIGN KEY (order_id)
        REFERENCES public."order" (order_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.carport
    ADD CONSTRAINT carport_order_id_fkey1 FOREIGN KEY (order_id)
        REFERENCES public."order" (order_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.carport
    ADD CONSTRAINT carport_order_id_fkey2 FOREIGN KEY (order_id)
        REFERENCES public."order" (order_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.carport
    ADD CONSTRAINT carport_order_id_fkey3 FOREIGN KEY (order_id)
        REFERENCES public."order" (order_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.carport_roof
    ADD CONSTRAINT carport_roof_carport_id_fkey FOREIGN KEY (carport_id)
        REFERENCES public.carport (carport_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.carport_roof
    ADD CONSTRAINT carport_roof_carport_id_fkey1 FOREIGN KEY (carport_id)
        REFERENCES public.carport (carport_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.carport_roof
    ADD CONSTRAINT carport_roof_carport_id_fkey2 FOREIGN KEY (carport_id)
        REFERENCES public.carport (carport_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.carport_roof
    ADD CONSTRAINT carport_roof_carport_id_fkey3 FOREIGN KEY (carport_id)
        REFERENCES public.carport (carport_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.carport_shed
    ADD CONSTRAINT carport_shed_carport_id_fkey FOREIGN KEY (carport_id)
        REFERENCES public.carport (carport_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.carport_shed
    ADD CONSTRAINT carport_shed_carport_id_fkey1 FOREIGN KEY (carport_id)
        REFERENCES public.carport (carport_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.carport_shed
    ADD CONSTRAINT shed_carport_id_fkey FOREIGN KEY (carport_id)
        REFERENCES public.carport (carport_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.carport_shed
    ADD CONSTRAINT shed_carport_id_fkey1 FOREIGN KEY (carport_id)
        REFERENCES public.carport (carport_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.contact_info
    ADD CONSTRAINT contact_info_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public."user" (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT order_contact_info_id_fkey FOREIGN KEY (contact_info_id)
        REFERENCES public.contact_info (contact_info_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT order_contact_info_id_fkey1 FOREIGN KEY (contact_info_id)
        REFERENCES public.contact_info (contact_info_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.specific
    ADD CONSTRAINT specific_material_id_fkey FOREIGN KEY (material_id)
        REFERENCES public.material (material_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.specific
    ADD CONSTRAINT specific_material_id_fkey1 FOREIGN KEY (material_id)
        REFERENCES public.material (material_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.specific
    ADD CONSTRAINT specific_material_id_fkey2 FOREIGN KEY (material_id)
        REFERENCES public.material (material_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.specific
    ADD CONSTRAINT specific_material_id_fkey3 FOREIGN KEY (material_id)
        REFERENCES public.material (material_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.specific
    ADD CONSTRAINT specific_material_id_fkey4 FOREIGN KEY (material_id)
        REFERENCES public.material (material_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.variant
    ADD CONSTRAINT variant_specific_id_fkey FOREIGN KEY (specific_id)
        REFERENCES public.specific (specific_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.variant
    ADD CONSTRAINT variant_specific_id_fkey1 FOREIGN KEY (specific_id)
        REFERENCES public.specific (specific_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.variant
    ADD CONSTRAINT variant_specific_id_fkey2 FOREIGN KEY (specific_id)
        REFERENCES public.specific (specific_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.variant
    ADD CONSTRAINT variant_specific_id_fkey3 FOREIGN KEY (specific_id)
        REFERENCES public.specific (specific_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.variant
    ADD CONSTRAINT variant_specific_id_fkey4 FOREIGN KEY (specific_id)
        REFERENCES public.specific (specific_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;

END;